plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-bump.js
    spec: bundles/@yarnpkg/plugin-bump.js
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.js
