on:
  push:
    tags:
      - "v*"

name: Publish the plugin

jobs:
  build-and-publish:
    name: Build w/ Node.js and publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install
        shell: bash

      - name: Build artifact
        run: yarn build

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload artifact
        id: upload-release-asset
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bundles/@yarnpkg/plugin-bump.js
          asset_name: plugin-bump.js
          asset_content_type: application/javascript
